/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VistaControlador;

import javax.swing.JOptionPane;
import Modelo.BBDD;
import Modelo.Ficheros;
import Modelo.Metodos;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.Timer;

/**
 *
 * @author USER
 */
public class Principal extends javax.swing.JFrame {

    private String username;
    UsuarioNuevo AuxUser;
    Login AuxLogin;
    private int mouseX, mouseY;
    private boolean mousePressed;
    
    public Principal() {
        initComponents();

    }

    public Principal(String username) {
        this.username = username;
        initComponents();
        BarraSupLabel.setText(this.getClass().getSimpleName());
        agregarText();
        Metodos.habilitarArrastre(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLateralPrincipal = new javax.swing.JPanel();
        botonModificarContrasenia = new javax.swing.JButton();
        botonNuevoUsuario = new javax.swing.JButton();
        botonCerrarSesion = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mensajeLogueadoName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTextoPrincipal = new javax.swing.JTextArea();
        panelSuperiorPrincipal = new javax.swing.JPanel();
        cerrarPrincipal = new javax.swing.JLabel();
        minimizarPrincipal = new javax.swing.JLabel();
        BarraSupLabel = new javax.swing.JLabel();
        barraEstadoPrincipal = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuFicheroPrincipal = new javax.swing.JMenu();
        botonGuardarTextArea = new javax.swing.JMenuItem();
        botonLeerTextArea = new javax.swing.JMenuItem();
        menuEdicionPrincipal = new javax.swing.JMenu();
        botonEdicionColor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");
        setUndecorated(true);

        panelLateralPrincipal.setBackground(new java.awt.Color(102, 165, 173));
        panelLateralPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 59, 70), 2));

        botonModificarContrasenia.setBackground(new java.awt.Color(7, 87, 91));
        botonModificarContrasenia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonModificarContrasenia.setForeground(new java.awt.Color(255, 255, 255));
        botonModificarContrasenia.setText("Modificar Contraseña");
        botonModificarContrasenia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonModificarContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarContraseniaActionPerformed(evt);
            }
        });

        botonNuevoUsuario.setBackground(new java.awt.Color(7, 87, 91));
        botonNuevoUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonNuevoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        botonNuevoUsuario.setText("Nuevo Usuario");
        botonNuevoUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoUsuarioActionPerformed(evt);
            }
        });

        botonCerrarSesion.setBackground(new java.awt.Color(7, 87, 91));
        botonCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        botonCerrarSesion.setText("Cerrar Sesion");
        botonCerrarSesion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarSesionActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\GitHub\\practica3.2\\mavenPractica3_2\\src\\main\\resources\\imageUsuario.png")); // NOI18N
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Bienvenid@");

        mensajeLogueadoName.setBackground(new java.awt.Color(0, 0, 0));
        mensajeLogueadoName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mensajeLogueadoName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelLateralPrincipalLayout = new javax.swing.GroupLayout(panelLateralPrincipal);
        panelLateralPrincipal.setLayout(panelLateralPrincipalLayout);
        panelLateralPrincipalLayout.setHorizontalGroup(
            panelLateralPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLateralPrincipalLayout.createSequentialGroup()
                .addGroup(panelLateralPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLateralPrincipalLayout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(mensajeLogueadoName, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLateralPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelLateralPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonCerrarSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonNuevoUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonModificarContrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLateralPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelLateralPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLateralPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLateralPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );
        panelLateralPrincipalLayout.setVerticalGroup(
            panelLateralPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLateralPrincipalLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addComponent(mensajeLogueadoName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(botonModificarContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        areaTextoPrincipal.setColumns(20);
        areaTextoPrincipal.setRows(5);
        jScrollPane1.setViewportView(areaTextoPrincipal);

        panelSuperiorPrincipal.setBackground(new java.awt.Color(7, 87, 91));
        panelSuperiorPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 59, 70), 2));
        panelSuperiorPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        panelSuperiorPrincipal.setLayout(null);

        cerrarPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cerrarPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        cerrarPrincipal.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\GitHub\\practica3.2\\mavenPractica3_2\\src\\main\\resources\\icons8-cerrar-ventana-52.png")); // NOI18N
        cerrarPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarPrincipalMouseClicked(evt);
            }
        });
        panelSuperiorPrincipal.add(cerrarPrincipal);
        cerrarPrincipal.setBounds(650, 10, 25, 25);

        minimizarPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        minimizarPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        minimizarPrincipal.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\GitHub\\practica3.2\\mavenPractica3_2\\src\\main\\resources\\icons8-minimizar-50-removebg-preview.png")); // NOI18N
        minimizarPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarPrincipalMouseClicked(evt);
            }
        });
        panelSuperiorPrincipal.add(minimizarPrincipal);
        minimizarPrincipal.setBounds(620, 10, 30, 30);

        BarraSupLabel.setBackground(new java.awt.Color(255, 255, 255));
        BarraSupLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BarraSupLabel.setForeground(new java.awt.Color(255, 255, 255));
        BarraSupLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BarraSupLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSuperiorPrincipal.add(BarraSupLabel);
        BarraSupLabel.setBounds(250, 10, 200, 30);

        barraEstadoPrincipal.setBackground(new java.awt.Color(102, 165, 173));
        barraEstadoPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jMenuBar2.setBackground(new java.awt.Color(0, 59, 70));

        menuFicheroPrincipal.setText("Fichero");

        botonGuardarTextArea.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        botonGuardarTextArea.setText("Guardar");
        botonGuardarTextArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGuardarTextAreaMouseClicked(evt);
            }
        });
        botonGuardarTextArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarTextAreaActionPerformed(evt);
            }
        });
        menuFicheroPrincipal.add(botonGuardarTextArea);

        botonLeerTextArea.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        botonLeerTextArea.setText("Abrir");
        botonLeerTextArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLeerTextAreaActionPerformed(evt);
            }
        });
        menuFicheroPrincipal.add(botonLeerTextArea);

        jMenuBar2.add(menuFicheroPrincipal);

        menuEdicionPrincipal.setText("Edición");

        botonEdicionColor.setText("Cambiar Color UI");
        botonEdicionColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEdicionColorActionPerformed(evt);
            }
        });
        menuEdicionPrincipal.add(botonEdicionColor);

        jMenuBar2.add(menuEdicionPrincipal);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSuperiorPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelLateralPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barraEstadoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelSuperiorPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(barraEstadoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLateralPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoUsuarioActionPerformed
        abrirFrameNuevoUsuario();
    }//GEN-LAST:event_botonNuevoUsuarioActionPerformed

    private void botonModificarContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarContraseniaActionPerformed
        String contraseniaNueva = JOptionPane.showInputDialog("Introduce la nueva contraseña:");
        BBDD.modificarContrasenia(username, contraseniaNueva);
        barraEstadoTiempo("Contraseña Modificada con EXITO!");
    }//GEN-LAST:event_botonModificarContraseniaActionPerformed

    private void botonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarSesionActionPerformed
        AuxLogin = new Login();
        AuxLogin.setVisible(true);
        AuxLogin.pack();
        AuxLogin.setLocationRelativeTo(this);
        AuxLogin.cambiarColorLogin(panelLateralPrincipal.getBackground(),panelSuperiorPrincipal.getBackground());
        this.dispose();
        //new Principal().setVisible(false);
    }//GEN-LAST:event_botonCerrarSesionActionPerformed

    private void cerrarPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarPrincipalMouseClicked
        this.dispose();
    }//GEN-LAST:event_cerrarPrincipalMouseClicked

    private void minimizarPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarPrincipalMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_minimizarPrincipalMouseClicked

    private void botonGuardarTextAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarTextAreaMouseClicked


    }//GEN-LAST:event_botonGuardarTextAreaMouseClicked

    private void botonGuardarTextAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarTextAreaActionPerformed
        JFileChooser seleccionarArchivo = new JFileChooser();
        int solucion = seleccionarArchivo.showSaveDialog(null);

        if (JFileChooser.APPROVE_OPTION == solucion) {
            try {
                Ficheros.guardarFichero(areaTextoPrincipal.getText(), seleccionarArchivo);
            } catch (IOException ex) {
                barraEstadoTiempo("No se ha podido Guardar el Fichero");
            }
            barraEstadoTiempo("Texto Guardado con EXITO!");
        }

    }//GEN-LAST:event_botonGuardarTextAreaActionPerformed

    private void botonLeerTextAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLeerTextAreaActionPerformed
        JFileChooser seleccionarArchivo = new JFileChooser();
        int solucion = seleccionarArchivo.showOpenDialog(null);

        if (JFileChooser.APPROVE_OPTION == solucion) {
            try {
                areaTextoPrincipal.setText(Ficheros.leerFichero(seleccionarArchivo));
            } catch (IOException ex) {
                barraEstadoTiempo("No se ha podido Cargar el Fichero");
            }
            barraEstadoTiempo("Texto Cargado con EXITO!");
        }

    }//GEN-LAST:event_botonLeerTextAreaActionPerformed

    private void botonEdicionColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEdicionColorActionPerformed
        JColorChooser elegir = new JColorChooser();
        Color colorSeleccionado = elegir.showDialog(null, "Selecciona un Color", panelLateralPrincipal.getBackground());       
        if (colorSeleccionado != null) {                    
            Color colorSel2 = colorSeleccionado.darker(); //Cojo el color de arrriba y le doy oscuridad y lo pongo en una variable Color para utilizarla.
            cambiarColorPrincipal(colorSel2, colorSeleccionado); 
            barraEstadoTiempo("Se ha cambiado de COLOR la UI");
        }
    }//GEN-LAST:event_botonEdicionColorActionPerformed
    
    
    private void agregarText() {
        mensajeLogueadoName.setText("El usuario " + this.username + " esta logueado");
    }

    private void barraEstadoTiempo(String entrada) {
        barraEstadoPrincipal.setText(entrada);
        int delay = 5000;
        Timer timer = new Timer(delay, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                barraEstadoPrincipal.setText("");
            }
        });
        timer.setRepeats(false); // Para que el temporizador solo se ejecute una vez
        timer.start();
    }
    
    private void abrirFrameNuevoUsuario() {
        AuxUser = new UsuarioNuevo();
        AuxUser.setVisible(true);
        AuxUser.pack();
        AuxUser.setLocationRelativeTo(this);
        AuxUser.cambiarColorUsuarioNuevo(panelSuperiorPrincipal.getBackground(), panelLateralPrincipal.getBackground());
    }

    public void cambiarColorPrincipal(Color oscuro, Color claro) {
        panelLateralPrincipal.setBackground(claro);
        panelSuperiorPrincipal.setBackground(oscuro);
        botonModificarContrasenia.setBackground(oscuro);
        botonCerrarSesion.setBackground(oscuro);
        botonNuevoUsuario.setBackground(oscuro);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BarraSupLabel;
    private javax.swing.JTextArea areaTextoPrincipal;
    private javax.swing.JLabel barraEstadoPrincipal;
    private javax.swing.JButton botonCerrarSesion;
    private javax.swing.JMenuItem botonEdicionColor;
    private javax.swing.JMenuItem botonGuardarTextArea;
    private javax.swing.JMenuItem botonLeerTextArea;
    private javax.swing.JButton botonModificarContrasenia;
    private javax.swing.JButton botonNuevoUsuario;
    private javax.swing.JLabel cerrarPrincipal;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mensajeLogueadoName;
    private javax.swing.JMenu menuEdicionPrincipal;
    private javax.swing.JMenu menuFicheroPrincipal;
    private javax.swing.JLabel minimizarPrincipal;
    private javax.swing.JPanel panelLateralPrincipal;
    private javax.swing.JPanel panelSuperiorPrincipal;
    // End of variables declaration//GEN-END:variables
}
